export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const HANDLE_ERRORS = "HANDLE_ERRORS";
export const HANDLE_FORM_ERRORS = "HANDLE_FORM_ERRORS";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_TOKEN = "SET_TOKEN";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_CURRENTUSER = "LOGOUT_CURRENTUSER";
export const LOAD_CURRENTUSER = "LOAD_CURRENTUSER";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const UPDATE_CURRENTUSER = "UPDATE_CURRENTUSER";
export const LOAD_LISTINGS = "LOAD_LISTINGS";
export const CREATE_LISTING = "CREATE_LISTING";

// ADMIN ACTION TYPES
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_GUESTS = "GET_GUESTS";
export const ADD_NEW_EMPLOYEE = "ADD_NEW_EMPLOYEE";
export const ADMIN_SHOW_USER = "ADMIN_SHOW_USER";
export const ADMIN_UPDATE_USER = "ADMIN_UPDATE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";