export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const HANDLE_ERRORS = "HANDLE_ERRORS";
export const HANDLE_FORM_ERRORS = "HANDLE_FORM_ERRORS";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_TOKEN = "SET_TOKEN";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_CURRENTUSER = "LOGOUT_CURRENTUSER";
export const LOAD_CURRENTUSER = "LOAD_CURRENTUSER";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const UPDATE_CURRENTUSER = "UPDATE_CURRENTUSER";

// ADMIN ACTION TYPES
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_GUESTS = "GET_GUESTS";
export const ADD_NEW_EMPLOYEE = "ADD_NEW_EMPLOYEE";
export const ADMIN_SHOW_USER = "ADMIN_SHOW_USER";
export const ADMIN_UPDATE_USER = "ADMIN_UPDATE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const ADMIN_LOAD_LISTINGS = "ADMIN_LOAD_LISTINGS";

// LISTINGS ACTION TYPES
export const GET_ALL_LISTINGS = "GET_ALL_LISTINGS";
export const CREATE_NEW_LISTNG = "CREATE_NEW_LISTNG";
export const UPDATE_LISTING = "UPDATE_LISTING";
export const DELETE_LISTING = "DELETE_LISTING";
export const SHOW_LISTING = "SHOW_LISTING";